begin;
-- Execute inside a transaction and roll back all fixture reports.
do $$
declare
    actor public.profiles%rowtype;
    citizen uuid;
    admin_id uuid;
    other_lgu public.profiles%rowtype;
    main public.incident_report%rowtype;
    followup public.incident_report%rowtype;
    context record;
    rejected boolean;
begin
    select * into actor from public.profiles where role in ('lgu','lgu_frontliner','lgu_headmaster') and account_status='active' and municipality_id is not null limit 1;
    if not found then raise exception 'No active LGU test account with a municipality is available.'; end if;
    select id into admin_id from public.profiles where role in ('national_admin','provincial_admin') and account_status='active' limit 1;
    assert admin_id is not null, 'Active admin fixture needed';
    perform set_config('request.jwt.claim.sub',actor.id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',actor.id,'role','authenticated')::text,true);
    select * into main from public.submit_situational_report('Workflow verification', 'Ongoing', 'Initial test context');
    assert main.parent_report_id is null, 'A submission without a parent must be a main report';
    assert main.situation_status='Ongoing', 'Initial operational status must be saved';
    assert main.status='Pending_AI', 'A new main report must wait for acceptance';
    rejected := false;
    begin perform public.get_situational_report_context(main.report_id);
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Pending reports cannot be selected through context RPC';
    rejected := false;
    begin perform public.submit_situational_report('Bypass', 'Resolved', 'Pending parent', main.report_id, null, 'Ongoing');
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Pending parents must reject linked RPC submissions';
    rejected := false;
    begin insert into public.incident_report(user_id,report_type,hazard_type,description,status,municipality_id,parent_report_id,situation_status)
    values(actor.id,'situational_report','[SITUATIONAL] Bypass','Pending direct insert','Pending_AI',actor.municipality_id,main.report_id,'Resolved');
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Pending parents must reject direct inserts';
    rejected := false;
    begin update public.incident_report set status='Verified' where report_id=main.report_id;
    exception when insufficient_privilege then rejected:=true; end;
    assert rejected, 'LGU cannot approve its own report';
    perform set_config('request.jwt.claim.sub',admin_id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',admin_id,'role','authenticated')::text,true);
    update public.incident_report set status='Verified' where report_id=main.report_id;
    perform set_config('request.jwt.claim.sub',actor.id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',actor.id,'role','authenticated')::text,true);
    select * into context from public.get_situational_report_context(main.report_id);
    assert context.current_status='Ongoing' and context.title='Workflow verification', 'Context must read the saved title/status';
    select * into followup from public.submit_situational_report('Mismatched client title', 'Resolved', 'Follow-up context', main.report_id, null, 'Ongoing');
    assert followup.parent_report_id=main.report_id, 'Follow-up must use the UUID relationship';
    assert followup.hazard_type=main.hazard_type, 'Server must use the parent title';
    select * into context from public.get_situational_report_context(main.report_id);
    assert context.current_status='Resolved', 'Main current status must advance atomically';
    rejected := false;
    begin perform public.submit_situational_report('Any title', 'Resolved', 'Repeated status', main.report_id, null, 'Resolved');
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Backend must reject repeating the current status';
    rejected := false;
    begin perform public.submit_situational_report('Any title', 'Pending Escalation', 'Stale snapshot', main.report_id, null, 'Ongoing');
    exception when serialization_failure then rejected:=true; end;
    assert rejected, 'Backend must reject stale status snapshots';
    rejected := false;
    begin insert into public.incident_report(user_id,report_type,hazard_type,description,status,municipality_id,parent_report_id,situation_status)
    values(actor.id,'situational_report','[SITUATIONAL] Wrong title','Bypass attempt','Pending_AI',actor.municipality_id,main.report_id,'Resolved');
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Direct inserts must also reject repeated current status';
    insert into public.incident_report(user_id,report_type,hazard_type,description,status,municipality_id,parent_report_id,situation_status)
    values(actor.id,'situational_report','[SITUATIONAL] Wrong title','Direct follow-up','Pending_AI',actor.municipality_id,main.report_id,'Pending Escalation') returning * into followup;
    assert followup.hazard_type=main.hazard_type, 'Direct inserts must also inherit the parent title';
    select * into context from public.get_situational_report_context(main.report_id);
    assert context.current_status='Pending Escalation', 'The latest follow-up must be the current status';
    rejected := false;
    begin update public.incident_report set situation_status='Ongoing' where report_id=main.report_id;
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Operational status cannot bypass follow-up history';
    rejected := false;
    begin perform public.submit_situational_report('Any title','Ongoing','Nested main',followup.report_id,null,'Pending Escalation');
    exception when check_violation or no_data_found then rejected:=true; end;
    assert rejected, 'An update cannot become an unrelated main report';
    select * into followup from public.submit_situational_report('Standalone report','Resolved','[Linked Situational Report: '||main.report_id||'] injected metadata');
    assert followup.parent_report_id is null and followup.description not like '%[Linked Situational Report:%', 'Description text cannot invent a parent relationship';
    perform set_config('request.jwt.claim.sub',admin_id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',admin_id,'role','authenticated')::text,true);
    update public.incident_report set status='Rejected' where report_id=main.report_id;
    perform set_config('request.jwt.claim.sub',actor.id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',actor.id,'role','authenticated')::text,true);
    rejected:=false;
    begin perform public.submit_situational_report('Revoked','Ongoing','Revoked acceptance',main.report_id,null,'Pending Escalation');
    exception when check_violation then rejected:=true; end;
    assert rejected, 'Revoked acceptance must reject stale selections';
    perform set_config('request.jwt.claim.sub',admin_id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',admin_id,'role','authenticated')::text,true);
    update public.incident_report set status='Verified' where report_id=main.report_id;
    perform set_config('request.jwt.claim.sub',actor.id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',actor.id,'role','authenticated')::text,true);
    perform public.submit_situational_report('Verified parent','Ongoing','Verified also accepted',main.report_id,null,'Pending Escalation');
    select * into other_lgu from public.profiles where role in ('lgu','lgu_frontliner','lgu_headmaster') and account_status='active' and municipality_id is not null and municipality_id<>actor.municipality_id limit 1;
    assert other_lgu.id is not null, 'A second municipality fixture is needed';
    perform set_config('request.jwt.claim.sub',other_lgu.id::text,true);
    perform set_config('request.jwt.claims',json_build_object('sub',other_lgu.id,'role','authenticated')::text,true);
    rejected:=false;
    begin perform public.submit_situational_report('Wrong LGU','Resolved','Cross municipality',main.report_id,null,'Ongoing');
    exception when insufficient_privilege then rejected:=true; end;
    assert rejected, 'Other municipalities cannot link accepted reports';
    select id into citizen from public.profiles where role='citizen' limit 1;
    if citizen is not null then
        perform set_config('request.jwt.claim.sub',citizen::text,true);
        perform set_config('request.jwt.claims',json_build_object('sub',citizen,'role','authenticated')::text,true);
        rejected:=false;
        begin perform public.submit_situational_report('Unauthorized','Ongoing','Test');
        exception when insufficient_privilege then rejected:=true; end;
        assert rejected, 'Citizen accounts cannot submit LGU situational reports';
    end if;
    assert not has_function_privilege('anon','public.submit_situational_report(text,text,text,uuid,text,text)','EXECUTE'), 'Anonymous RPC access must be denied';
end $$;
select 'PASS: standalone, parent UUID, server title inheritance, latest status, repeated-status rejection, stale snapshots, acceptance/revocation, admin-only approval, municipality scope, direct-write guards and LGU authorization' as verification;

rollback;
